# Generated by Django 2.2 on 2020-07-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio', '0002_remove_categoria_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre1',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='venta',
        ),
    ]
