# Generated by Django 2.2 on 2020-07-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio', '0005_auto_20200701_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proeve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Comercio.Proveedore'),
            preserve_default=False,
        ),
    ]
