# Generated by Django 2.2 on 2020-07-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio', '0006_producto_proeve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proeve',
        ),
    ]
